package org.acme.bot.infrastructure.persistence.entity;


import jakarta.persistence.*;

/**
 *
 * Entity of the Role Class
 *
 */
@Entity
@Table(name="roles")
public class RoleEntity {

    /**
     *
     * Primary Key
     * Auto generated by the database to ensure efficient indexing and joins
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true,nullable=false)
    private String name;


    /**
     * Default constructor required by the JPA specification
     */

    public RoleEntity() {

    }

    public RoleEntity(String name) {
        this.name = name;
    }


    /**
     *
     * Getter and Setter
     *
     */

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
